all: 
	pileupCalc.py -i Cert_271036-284044_13TeV_23Sep2016ReReco_Collisions16_JSON.txt --inputLumiJSON pileup_latest.txt --calcMode true --minBiasXsec 69200 --maxPileupBin 200 --numPileupBins 1000 pileup_Sep16ReReco.root

clean:
	rm pileup_Sep16ReReco.root
